image: node:10

stages:
  - lint
  - test

lint:
  stage: lint
  except:
    - triggers
  tags:
    - docker
  image: node:10
  script:
    - npm install
    - npm run lint -- --no-fix

test_unit:
  stage: test
  except:
    - triggers
  tags:
    - docker
  image: node:10
  script:
   - npm install
   - npm run test:unit

test_e2e:
  stage: test
  except:
    - triggers
  tags:
    - docker
  environment:
    name: production
  image: cypress/base:10
  script:
    - npm install
    - npm run test:e2e -- --headless

